-- MySQL Script generated by MySQL Workbench
-- Fri 02 Oct 2015 11:20:07 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clvwrdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clvwrdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clvwrdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `clvwrdb` ;

-- -----------------------------------------------------
-- Table `clvwrdb`.`tblCluster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clvwrdb`.`tblCluster` ;

CREATE TABLE IF NOT EXISTS `clvwrdb`.`tblCluster` (
  `idCluster` INT NOT NULL AUTO_INCREMENT,
  `dtIPAddress` VARCHAR(255) NULL,
  `dtCaption` VARCHAR(255) NULL,
  `dtEnabled` TINYINT(1) NULL,
  PRIMARY KEY (`idCluster`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
